name: API Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: |
          cd api
          mkdir API_Reports

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra

      - name: Run Appium Tests
        run: | 
          newman run "api/API_Asessment.postman_collection.json" -r htmlextra --reporter-htmlextra-export api/API_Reports/report.html
        
      - name: Publish Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: api/API_Reports
