name: Mobile Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]  
        target: [default]
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: 21
        
    - uses: actions/setup-node@v4.3.0
      with:
       node-version: 20
    - run: |
            npm install -g appium@v1.22.3
            appium -v
            appium &>/dev/null &
            
    - name: Run Appium Tests
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with:
        api-level: ${{matrix.api-level}}
        target: ${{matrix.target}}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test 

    - name: Publish Report
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Reports
        path: /Users/runner/work/
